name: ✅ Build Status Check
run-name: ✅ Build Status Check (${{ github.base_ref }} branch)

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  # FinalEngine.Audio
  build_audio:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Audio dependencies
      run: dotnet restore FinalEngine.Audio/FinalEngine.Audio.csproj

    - name: Build FinalEngine.Audio
      run: dotnet build FinalEngine.Audio/FinalEngine.Audio.csproj --no-restore

  # FinalEngine.Audio.OpenAL
  build_audio_openal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Audio.OpenAL dependencies
      run: dotnet restore FinalEngine.Audio.OpenAL/FinalEngine.Audio.OpenAL.csproj

    - name: Build FinalEngine.Audio.OpenAL
      run: dotnet build FinalEngine.Audio.OpenAL/FinalEngine.Audio.OpenAL.csproj --no-restore

  # FinalEngine.ECS
  build_ecs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.ECS dependencies
      run: dotnet restore FinalEngine.ECS/FinalEngine.ECS.csproj

    - name: Build FinalEngine.ECS
      run: dotnet build FinalEngine.ECS/FinalEngine.ECS.csproj --no-restore

  # FinalEngine.ECS.Components
  build_ecs_components:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.ECS.Components dependencies
      run: dotnet restore FinalEngine.ECS.Components/FinalEngine.ECS.Components.csproj

    - name: Build FinalEngine.ECS.Components
      run: dotnet build FinalEngine.ECS.Components/FinalEngine.ECS.Components.csproj --no-restore

  # FinalEngine.Editor.Common
  build_editor_common:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Editor.Common dependencies
      run: dotnet restore FinalEngine.Editor.Common/FinalEngine.Editor.Common.csproj

    - name: Build FinalEngine.Editor.Common
      run: dotnet build FinalEngine.Editor.Common/FinalEngine.Editor.Common.csproj --no-restore

  # FinalEngine.Editor.Desktop
  build_editor_desktop:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Editor.Desktop dependencies
      run: dotnet restore FinalEngine.Editor.Desktop/FinalEngine.Editor.Desktop.csproj

    - name: Build FinalEngine.Editor.Desktop
      run: dotnet build FinalEngine.Editor.Desktop/FinalEngine.Editor.Desktop.csproj --no-restore

  # FinalEngine.Editor.ViewModels
  build_editor_view_models:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Editor.ViewModels dependencies
      run: dotnet restore FinalEngine.Editor.ViewModels/FinalEngine.Editor.ViewModels.csproj

    - name: Build FinalEngine.Editor.ViewModels
      run: dotnet build FinalEngine.Editor.ViewModels/FinalEngine.Editor.ViewModels.csproj --no-restore

  # FinalEngine.Extensions.Resources
  build_extensions_resources:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Extensions.Resources dependencies
      run: dotnet restore FinalEngine.Extensions.Resources/FinalEngine.Extensions.Resources.csproj

    - name: Build FinalEngine.Extensions.Resources
      run: dotnet build FinalEngine.Extensions.Resources/FinalEngine.Extensions.Resources.csproj --no-restore

  # FinalEngine.Input
  build_input:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Input dependencies
      run: dotnet restore FinalEngine.Input/FinalEngine.Input.csproj

    - name: Build FinalEngine.Input
      run: dotnet build FinalEngine.Input/FinalEngine.Input.csproj --no-restore

  # FinalEngine.Maths
  build_maths:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Maths dependencies
      run: dotnet restore FinalEngine.Maths/FinalEngine.Maths.csproj

    - name: Build FinalEngine.Maths
      run: dotnet build FinalEngine.Maths/FinalEngine.Maths.csproj --no-restore

  # FinalEngine.Platform
  build_platform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Platform dependencies
      run: dotnet restore FinalEngine.Platform/FinalEngine.Platform.csproj

    - name: Build FinalEngine.Platform
      run: dotnet build FinalEngine.Platform/FinalEngine.Platform.csproj --no-restore

  # FinalEngine.Platform.Desktop
  build_platform_desktop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Platform.Desktop dependencies
      run: dotnet restore FinalEngine.Platform.Desktop/FinalEngine.Platform.Desktop.csproj

    - name: Build FinalEngine.Platform.Desktop
      run: dotnet build FinalEngine.Platform.Desktop/FinalEngine.Platform.Desktop.csproj --no-restore

  # FinalEngine.Rendering
  build_rendering:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Rendering dependencies
      run: dotnet restore FinalEngine.Rendering/FinalEngine.Rendering.csproj

    - name: Build FinalEngine.Rendering
      run: dotnet build FinalEngine.Rendering/FinalEngine.Rendering.csproj --no-restore

  # FinalEngine.Rendering.OpenGL
  build_rendering_opengl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Rendering.OpenGL dependencies
      run: dotnet restore FinalEngine.Rendering.OpenGL/FinalEngine.Rendering.OpenGL.csproj

    - name: Build FinalEngine.Rendering.OpenGL
      run: dotnet build FinalEngine.Rendering.OpenGL/FinalEngine.Rendering.OpenGL.csproj --no-restore

  # FinalEngine.Resources
  build_resources:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Resources dependencies
      run: dotnet restore FinalEngine.Resources/FinalEngine.Resources.csproj

    - name: Build FinalEngine.Resources
      run: dotnet build FinalEngine.Resources/FinalEngine.Resources.csproj --no-restore

  # FinalEngine.Runtime
  build_runtime:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Runtime dependencies
      run: dotnet restore FinalEngine.Runtime/FinalEngine.Runtime.csproj

    - name: Build FinalEngine.Runtime
      run: dotnet build FinalEngine.Runtime/FinalEngine.Runtime.csproj --no-restore

  # FinalEngine.Utilities
  build_utilities:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Utilities dependencies
      run: dotnet restore FinalEngine.Utilities/FinalEngine.Utilities.csproj

    - name: Build FinalEngine.Utilities
      run: dotnet build FinalEngine.Utilities/FinalEngine.Utilities.csproj --no-restore
